apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prepro-web-deployment
  labels:
    app: prepro-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prepro-web
    spec:
      containers:
      - name: prepro-web
        image: docker.io/kikko/prepro-demo:0.0.16
        imagePullPolicy: Always
        volumeMounts:
        - name: secret
          mountPath: "/prepro/secret"
          readOnly: true
      volumes:
      - name: secret
        secret:
          secretName: prepro-web-firebase-secret
